sudo: false
dist: trusty
language: node_js
node_js:
  - 12

stages:
  - test
  - deploy

env:
  - TEST_SUITE=main
  - TEST_SUITE=tz TZ_LENGTH=2 TZ_INDEX=0
  - TEST_SUITE=tz TZ_LENGTH=2 TZ_INDEX=1
  - TEST_SUITE=node

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g yarn

branches:
  only:
    - master
    - "/v\\d+\\.\\d+\\.\\d+(-\\w+)?/"

script:
  - ./scripts/test/travis.sh

jobs:
  include:
    - stage: deploy
      if: tag IS present
      script: ./scripts/release/release.sh
    - stage: Coverage report
      script: ./scripts/test/coverageReport.sh

cache: yarn

addons:
  chrome: stable
  # sauce_connect: true
